### ISSUE TITLE
Bug compiling with CUDNN with 4.1.2

### ISSUE THREAD

**Issue by tadam98** [opencv/opencv#17372]
https://github.com/opencv/opencv/archive/4.1.2.zip

This version has a bug when compiling for CUDNN.
File cmake/FindCUDNN.cmake is faulty and needs two corrections:

1. location of libcudnn library is searched in the wrong file. It is seached in cudnn.h while it is in cudnn_version.h
2. The "set" creating the CUDNN version has a problem and needs to be modified.

```
In file cmake/FindCUDNN.cmake
Replace:
  file(READ "${CUDNN_INCLUDE_DIR}/cudnn.h" CUDNN_H_CONTENTS) 
With:
  file(READ "${CUDNN_INCLUDE_DIR}/cudnn_version.h" CUDNN_H_CONTENTS)
```

And replace:
 ```
 set(CUDNN_VERSION
    "${CUDNN_MAJOR_VERSION}.${CUDNN_MINOR_VERSION}.${CUDNN_PATCH_VERSION}"
    CACHE
    STRING
    "cuDNN version"
  )

# with:
  set(CUDNN_VERSION
    "${CUDNN_MAJOR_VERSION}.${CUDNN_MINOR_VERSION}.${CUDNN_PATCH_VERSION}"
  )
```
And now it compiles correctly.

```
 cmake \
 -D CMAKE_BUILD_TYPE=RELEASE \
 -D WITH_CUDA=ON \
 -D WITH_CUDNN=ON \
 -D OPENCV_DNN_CUDA=ON \
 -D CUDA_ARCH_PTX="" \
 -D CUDA_ARCH_BIN="5.3,6.2,7.2" \
 -D WITH_CUBLAS=ON \
 -D WITH_LIBV4L=ON \
 -D BUILD_opencv_python3=ON \
 -D BUILD_opencv_python2=OFF \
 -D BUILD_opencv_java=OFF \
 -D WITH_FFMPEG=ON \
 -D WITH_GSTREAMER=ON \
 -D WITH_TBB=ON \
 -D BUILD_TBB=ON \
 -D WITH_GTK=ON \
 -D BUILD_TESTS=OFF \
 -D BUILD_PERF_TESTS=OFF \
 -D BUILD_EXAMPLES=OFF \
 -D OPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.2/modules \
 ..
```

**Comment by YashasSamaga** [comment]
4.1.2 doesn't have cuDNN support.

There is a PR (#17238) trying to address this issue.

**Comment by tadam98** [comment]
Well….I fixed it see

https://github.com/opencv/opencv/issues/17372

Best,
Mickey
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by YashasSamaga** [comment]
@tadam98 Based on the comments in #17238, the cuDNN binaries have been split into pieces. While recognizing the version might allow the build to continue, you will probably end up with linking errors.

**Comment by YashasSamaga** [comment]
> location of libcudnn library is searched in the wrong file. It is seached in cudnn.h while it is in cudnn_version.h

That is for cuDNN 8.0 Early Access. The previous versions have the version information in `cudnn.h`. OpenCV works well with the older versions.

**Comment by tadam98** [comment]
I am compiling for the Jetson nano.

Sdkmanager installs 4.1.1 without CuDNN support. (It took me 3 days to cause sdkmanager to work with CLI as the gui version does not support the nano, only the Xavier). Also the ml docker has no CuDNN support. Which is shameful as all of us use the Jetson for ML.

I also managed to execute the sdk manager on a VirtualBox VM running Ubuntu. Using a “usb filter” the usb devices and be automatically reconnected to the vm.

If my fix will not work, I will try a higher OpenCV version.

Best,
Mickey

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
True, but I am working now with NVIDIA Jetson nano. Their default version is 4.1.1 comes without cudnn as their CUDA is version 10.2 and there is this problem of which file holds the cudnn vesion. (Even if it was in the correct file, there was another bug in FindCUDNN.cmake file).

I try to stay as close as possible to the NVIDIA package. As I am worried that higher versions of OpenCV may be problematic.

My patch can also work with 4.2.0 https://github.com/opencv/opencv/issues/16439

Best,
Mickey

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by YashasSamaga** [comment]
I am sorry. I have a bad habit of hitting the comment button too early. I have edited my replies which you can see on GitHub.

OpenCV 4.1.2 does not have any code that uses cuDNN. The CMake recognizes cuDNN but it is not really used anywhere in the code. OpenCV 4.2 and above makes use of cuDNN.

All existing stable releases of cuDNN have version information in `cudnn.h`. `cudnn_version.h` was introduced in cuDNN 8 which hasn't been released yet. NVIDIA shipped the "early access" version of cuDNN 8 in their images for their embedded devices. cuDNN 8 seems to have moved the version information to `cudnn_version.h`. It has also split the cuDNN binary into several pieces. OpenCV's CMake scripts haven't been updated to deal with this yet.

The current CMake setup finds the version in `cudnn.h` and links a single `cudnn.so` binary. This is the correct way for all the released versions of cuDNN. This won't work for cuDNN 8 which is what you have preassumably got. There is no release notes or documentation for cuDNN 8 EA that outlines the changes so that the cuDNN build setup can be fixed. Even if you get the CMake to recognize cuDNN 8, you will have linking problems at some stage (based on what others have reported in #17238).

I am guessing that you are using NVIDIA's image for Jetson which has cuDNN 8 and OpenCV 4.1.2 (which is almost a year old now). You need to install newer versions of OpenCV if you want to make use of cuDNN in OpenCV.

**Comment by tadam98** [comment]
Thank you for your advice. I will switch to 4.2.0.

My download from NVIDIA is very new as I installed the latest image for JetPack 4.4 Developer pack.
I was VERY surprised many things do not reflect the latest and greatest which is cause a lot of wasted time and effort.

Best,
Mickey

**Comment by tadam98** [comment]
Hi,

Compilation completed fine and simple dnn functions work such as:
net = cv2.dnn.readNetFromCaffe(args["prototxt"], args["model"])

But more advanced stuff like:
cv2.dnn.DNN_BACKEND_CUDA and cv2.dnn.DNN_TARGET_CUDA produce an error:
AttributeError: module 'cv2.dnn' has no attribute ' DNN_BACKEND_CUDA'
AttributeError: module 'cv2.dnn' has no attribute 'DNN_TARGET_CUDA'

So…4.2.0 is coming.

Best,
Mickey
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
I am compiling now OpenCV 4.2.0 for Jetson nano with CUDA 10.2/
The same fixed I made to cmake/FindCUDNN.cmake mus be made here as well or else the version 8.0.0 of libcudnn.so is not found in cudnn.h as it is on cudnn_version.h

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
I compiled 4.2.0 and I am getting an error.
See build information at the beginning and the FP16 error at the end.

```
cv2 version= 4.2.0
cv2 path= /usr/local/lib/python3.6/dist-packages/cv2/python-3.6/cv2.cpython-36m-aarch64-linux-gnu.so
cv2 Build Information=
General configuration for OpenCV 4.2.0 =====================================
  Version control:               unknown

  Extra modules:
    Location (extra):            /home/dlinano/Downloads/opencv_contrib/modules
    Version control (extra):     unknown

  Platform:
    Timestamp:                   2020-05-25T21:07:56Z
    Host:                        Linux 4.9.140-tegra aarch64
    CMake:                       3.10.2
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               RELEASE

  CPU/HW features:
    Baseline:                    NEON FP16
      required:                  NEON
      disabled:                  VFPV3

  C/C++:
    Built as dynamic libs?:      YES
    C++ Compiler:                /usr/bin/c++  (ver 7.5.0)
    C++ flags (Release):         -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -ffast-math -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections    -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--gc-sections
    Linker flags (Debug):        -Wl,--gc-sections
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          m pthread cudart_static -lpthread dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cudnn cufft -L/usr/local/cuda/lib64 -L/usr/lib/aarch64-linux-gnu
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot python3 quality reg rgbd saliency sfm shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    python2 world
    Disabled by dependency:      -
    Unavailable:                 cnn_3dobj cvv java js matlab ovis ts viz
    Applications:                examples apps
    Documentation:               NO
    Non-free algorithms:         YES

  GUI:
    GTK+:                        YES (ver 3.22.30)
      GThread :                  YES (ver 2.56.4)
      GtkGlExt:                  NO
    OpenGL support:              NO
    VTK support:                 NO

  Media I/O:
    ZLib:                        /usr/lib/aarch64-linux-gnu/libz.so (ver 1.2.11)
    JPEG:                        /usr/lib/aarch64-linux-gnu/libjpeg.so (ver 80)
    WEBP:                        build (ver encoder: 0x020e)
    PNG:                         /usr/lib/aarch64-linux-gnu/libpng.so (ver 1.6.34)
    TIFF:                        /usr/lib/aarch64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
    JPEG 2000:                   build (ver 1.900.1)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      YES (2.2.5)
    FFMPEG:                      YES
      avcodec:                   YES (57.107.100)
      avformat:                  YES (57.83.100)
      avutil:                    YES (55.78.100)
      swscale:                   YES (4.8.100)
      avresample:                YES (3.7.0)
    GStreamer:                   YES (1.14.5)
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.4)
    Custom HAL:                  YES (carotene (ver 0.0.1))
    Protobuf:                    build (3.5.1)

  NVIDIA CUDA:                   YES (ver 10.2, CUFFT CUBLAS FAST_MATH)
    NVIDIA GPU arch:             53 62 72
    NVIDIA PTX archs:

  cuDNN:                         YES (ver 8.0.0)

  OpenCL:                        YES (no extra features)
    Include path:                /home/dlinano/Downloads/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 /usr/bin/python3 (ver 3.6.9)
    Libraries:                   /usr/lib/aarch64-linux-gnu/libpython3.6m.so (ver 3.6.9)
    numpy:                       /usr/lib/python3/dist-packages/numpy/core/include (ver 1.13.3)
    install path:                lib/python3.6/dist-packages/cv2/python-3.6

  Python (for build):            /usr/bin/python2.7

  Java:
    ant:                         NO
    JNI:                         NO
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    /usr/local
-----------------------------------------------------------------


[INFO] setting preferable backend and target to CUDA...
[INFO] accessing video stream...
**Traceback (most recent call last):
  File "ssd_object_detection.py", line 77, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /home/dlinano/Downloads/opencv/modules/dnn/src/dnn.cpp:1304: error: (-215:Assertion failed) preferableBackend != DNN_BACKEND_OPENCV || preferableTarget == DNN_TARGET_CPU || preferableTarget == DNN_TARGET_OPENCL || preferableTarget == DNN_TARGET_OPENCL_FP16 in function 'setUpNet'**

```

**Comment by YashasSamaga** [comment]
@tadam98 Please share the code where you set the backend and target.

**Comment by tadam98** [comment]
OpenCV 4.2.0 compiled with CUDNN support.

I have CUDA 10.2 and cuDNN 8.0 that matches it for the Jetson Nano.


python3 ssd_object_detection.py<http://ssd_object_detection.py> \
  --prototxt MobileNetSSD_deploy.prototxt \
  --model MobileNetSSD_deploy.caffemodel \
  --input guitar.mp4 --output output.avi \
  --display 0 --use-gpu 1


I am getting the following error:

cv2 version= 4.2.0
cv2 path= /usr/local/lib/python3.6/dist-packages/cv2/python-3.6/cv2.cpython-36m-aarch64-linux-gnu.so<http://cv2.cpython-36m-aarch64-linux-gnu.so>
[INFO] setting preferable backend and target to CUDA...
[INFO] accessing video stream...
Traceback (most recent call last):
  File "ssd_object_detection.py<http://ssd_object_detection.py>", line 76, in <module>
    detections = net.forward()
cv2.error: OpenCV(4.2.0) /home/dlinano/Downloads/opencv/modules/dnn/src/dnn.cpp:1304: error: (-215:Assertion failed) preferableBackend != DNN_BACKEND_OPENCV || preferableTarget == DNN_TARGET_CPU || preferableTarget == DNN_TARGET_OPENCL || preferableTarget == DNN_TARGET_OPENCL_FP16 in function 'setUpNet'

**Comment by tadam98** [comment]
https://t.dripemail2.com/c/eyJhY2NvdW50X2lkIjoiNDc2ODQyOSIsImRlbGl2ZXJ5X2lkIjoia3ZjZjloaWp3c3V6dHFxa3N4N24iLCJ1cmwiOiJodHRwczovL3MzLXVzLXdlc3QtMi5hbWF6b25hd3MuY29tL3N0YXRpYy5weWltYWdlc2VhcmNoLmNvbS9vcGVuY3YtZG5uLWdwdS9vcGVuY3YtZG5uLWdwdS56aXA_X19zPXpic296d2V1Mmg1b3lmM2p2a2ZwIn0

This is the download link including the models.

________________________________

**Comment by tadam98** [comment]
See attached

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tadam98** [comment]
https://drive.google.com/folderview?id=1rotEOktKAFdQZhGJPr224A6aFpnZ3ubK

Try my google drive,
Mickey
________________________________
From: Mickey Cohen <tadam_98@hotmail.com>
Sent: Wednesday, May 27, 2020 3:24:15 PM
To: opencv/opencv <reply@reply.github.com>; opencv/opencv <opencv@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [opencv/opencv] Bug compiling with CUDNN with 4.1.2 (#17372)


See attached



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by YashasSamaga** [comment]
cuDNN 8 works with OpenCV now. Can we close this issue?

**Comment by tadam98** [comment]
It works with cuDNN 8. **But**, cuDNN 8 does not support BACKEND.
So the problem is with cuDNN 8 not with OpenCV.
Until NVIDIA corrects cuDNN - best avoid it with OpenCV (Any version).
At this point the issue can be closed.
