### ISSUE TITLE
Error executing cv::dnn::cuda4dnn::csl::cudnn::transform in PyOpenCV

### ISSUE THREAD

**Issue by zerovirus123** [opencv/opencv#17631]
##### System information (version)
- OpenCV => 4.2.0
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2019
- Environment => Anaconda Python 3.7

##### Detailed description
I have built OpenCV from source with CUDA enabled, and copied the generated .pyd file into my Anaconda environment directory. I want to use the module for running GPU accelerated RCNN detection.

For small unit detections the code works fine.

##### Steps to reproduce

```
import cv2.dnn
import numpy
import torch
import time

def detect_image_opencv(opt_window_size, opt_conf_thres, window, net):
        rows = opt_window_size
        cols = opt_window_size
    
        blob = cv2.dnn.blobFromImage(window, size=(opt_window_size, opt_window_size), 
                                     swapRB=True, crop=False, scalefactor=1)
            
        net.setInput(blob)
        networkOutput = net.forward()
        
        detection_output = []
        detection_output_append = detection_output.append
        
        for detection in networkOutput[0, 0]:
            score = float(detection[2])
            if score > opt_conf_thres:
                x1 = detection[3] * cols
                y1 = detection[4] * rows
                x2 = detection[5] * cols
                y2 = detection[6] * rows
        
                detection_output_append([x1, y1, x2, y2, score, score, score])
        
        output_tensor = torch.cuda.FloatTensor(detection_output)
        return output_tensor
    
weight = r'F:\Sliding_Windows\checkpoints\PT02_V1.pb'
config_file = r'F:\Sliding_Windows\config\PT02_V1.pbtxt'
net = cv2.dnn.readNetFromTensorflow(weight, config_file)
net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

input_window = cv2.imread(r"test_window_2.jpg")

start = time.time()
output_tensor = detect_image_opencv(1000, 0.5, input_window, net)
end = time.time()
print(output_tensor)
print("Time take: {}".format(end - start))
```

However, if I embed the detection code into a larger project, such a sliding windows, and looped over many times, the code throws an error at the net.forward() line.

```
error OpenCV(4.2.0) C:\Ocv_Bri_Build\opencv-4.2.0\modules\dnn\src\cuda4dnn\csl\cudnn/transform.hpp:116: error: (-217:Gpu API call) CUDNN_STATUS_EXECUTION_FAILED in function 'cv::dnn::cuda4dnn::csl::cudnn::transform'
```

Is this a build error, a dependency error or an import error? How should I approach such a bug?

**Comment by YashasSamaga** [comment]
It is a runtime error.

1. What version of cuDNN are you using?
2. What version of CUDA Toolkit are you using?
3. Do you have multiple versions of cuDNN or CUDA Toolkit installed?
4. If yes, check that the cuDNN binary used by OpenCV matches with the CUDA Toolkit version that is used.
5. Restart your computer

**Comment by zerovirus123** [comment]
1.) 7.6.5
2.) The CUDA Toolkit version in the install directory is 10.1. However, nvidia-SMI shows that the CUDA version is 10.2.
3.) There is only 1 version of cuDNN installed. I placed the cuDNN header and binaries into their respective folders. I may have installed CUDA 10.2, but had since replaced it with CUDA 10.1. However, the change doesn't show up in the nvidia-smi command.
4.) I compiled OpenCV with cuDNN 7.6.5. Is there a way for me to import cv2 and check the cuDNN backend version?
5.) Doesn't work.

**Comment by YashasSamaga** [comment]
> There is only 1 version of cuDNN installed. I placed the cuDNN header and binaries into their respective folders. I may have installed CUDA 10.2, but had since replaced it with CUDA 10.1. However, the change doesn't show up in the nvidia-smi command.

cuDNN binaries require a specific version of CUDA Toolkit. If your cuDNN requires 10.2, you must use 10.2. Can you purge the previous installation? (or maybe remove all installations of cuDNN and CUDA Toolkit and reinstall 10.2 and *cuDNN 7.6.5 for 10.2*)


>  I compiled OpenCV with cuDNN 7.6.5. Is there a way for me to import cv2 and check the cuDNN backend version?

You can find the versions in `CMakeCache.txt`.

**Comment by zerovirus123** [comment]
I built my OpenCV project using CUDA 10.1 (C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/). CMakeCache.txt shows that the cuDNN version is 7.6.5.

The nvidia-smi command returns shows that the CUDA version is 10.2. Is that the Toolkit or runtime API? I am pretty certain that I have uninstalled all CUDA 10.2 files, but the smi command doesn't correctly reflect that. Do you want some log files or source code to pinpoint the error?

**Comment by YashasSamaga** [comment]
@zerovirus123 Have you solved this? If not, can you try with OpenCV 4.4.0? It has lots of new diagnostics to catch problems that lead to the kind of errors you're facing.

**Comment by zerovirus123** [comment]
Hi @YashasSamaga. I have solved the problem. I reproduced the error for you with a code snippet in issue #17672.

**Comment by mhs-achyut** [comment]
Why is this issue closed? I am facing the same issue. Can anyone help me get to the solution?

Thanks,
Achyut

**Comment by maazullah96** [comment]
I am facing the same Issue .The error I am getting is 
![image](https://user-images.githubusercontent.com/30190807/110440950-0a10d300-80db-11eb-8d95-9aca794932d1.png)
The code I am using just for testing purpose is from[ this repository
](https://github.com/spmallick/learnopencv/tree/master/ObjectDetection-YOLO)

I have attached the CMAKECache.txt
[CMakeCache.txt](https://github.com/opencv/opencv/files/6106906/CMakeCache.txt)

**Comment by YashasSamaga** [comment]
> Why is this issue closed? I am facing the same issue. Can anyone help me get to the solution?

Are you getting the exact same exception?

@maazullah96 Do other CUDA applications work on your PC? Please try restarting your computer.

**Comment by YashasSamaga** [comment]
@maazullah96 If your application is written in python and uses multiprocessing, please check https://github.com/opencv/opencv/issues/17900
