### ISSUE TITLE
/opencv/modules/dnn/src/cuda4dnn/csl/stream.hpp:49: error: (-217:Gpu API call) 

### ISSUE THREAD

**Issue by rafale77** [opencv/opencv#17949]
##### System information (version)

- OpenCV => 4.4+
- Operating System / Platform => Ubuntu 64 Bit x64
- Compiler => GCC
- Cuda 11.0.194
- nvidia driver 450.51.05
- cudnn 8.0
##### Detailed description

Using the python library I am getting this error after a few seconds running a second instance of cudnn inference.

/opencv/modules/dnn/src/cuda4dnn/csl/stream.hpp:49: error: (-217:Gpu API call) an illegal memory access was encountered in function 'UniqueStream' which then crashes out python. Tested on both python3.7.5 and python3.8.5

##### Steps to reproduce

1st instance runs a caffee model. Never had a problem with it.
2nd instance either caffe of a tensorflow model leads to this same problem

Question: Can the library run multiple inference models within the same python instance?

**Comment by rafale77** [comment]
Additional info: I seem to have no problem when using the GPU for stream decoding on opencv and inferring with the CPU.

**Comment by YashasSamaga** [comment]
The exception was thrown when a stream was being created (implying the `Net` object was being created). The illegal memory access presumably happened even before you created the second `Net` object.

Running multiple inference models within the same python instance should work. Can you provide a reproducer?

**Comment by rafale77** [comment]
I just updated to the latest cudnn8.0.1 from the previous 8.0.0 and it seems to be a tiny bit better: I am now able to run 2 inferences for quit some time before seeing an error but once I load it up with 4, it crashes almost immediately with a similar error but not quite the same so I think you are right in the fact that the problem likely happen before the error pointer:
opencv/modules/dnn/src/cuda4dnn/csl/pointer.hpp:366: error: (-217:Gpu API call) misaligned address in function 'memcpy'

Not sure what you mean by a reproducer... can you give an example?
I run this under home-assistant and have written my own components to use opencv, loading for now 2 different inference models: the face detection SSD and the mobilenet v3 object detection.

**Comment by YashasSamaga** [comment]
> Not sure what you mean by a reproducer... can you give an example?

A code snippet that can reproduce the problem you're facing so that I can try it on my side. Can you share the model?

**Comment by rafale77** [comment]
https://github.com/rafale77/home-assistant/blob/dev/homeassistant/components/opencv/image_processing.py

I posted my component here. The video stream is from another homeassistant which is also running opencv:

https://github.com/rafale77/home-assistant/blob/dev/homeassistant/components/ffmpeg/camera.py

and I have been running this inference on a single instance for some time now:

https://github.com/rafale77/home-assistant/blob/dev/homeassistant/components/dlib_face_identify/image_processing.py

**Comment by YashasSamaga** [comment]
> face detection SSD and the mobilenet v3 object detection

do you have a link to these models?

**Comment by rafale77** [comment]
this is the caffe res10 model for face detection
https://github.com/rafale77/face_recognition_models/tree/master/face_recognition_models/models
and this is the mobilenetv3 model: 
https://github.com/opencv/opencv/pull/16760

**Comment by rafale77** [comment]
I can now confirm that running two different models within the same python instance is not a problem (I had a problem on the previous pre-released version of cudnn8). Somehow I am getting a memory error if I run the same model twice on cudnn8.0.1.

**Comment by rafale77** [comment]
@YashasSamaga, I switched my code to run your YoloV4 model and I am seeing the same problem. I can't run more than 2 concurrent instances of one same model without getting some weird memory issues. I started to think that I have a bad GPU but I am able to run 4 simultaneous streams within a single instance on a tensorrt framework so... I am not so sure anymore.

**Comment by rafale77** [comment]
I had an epiphany this evening and found out that the problem is resolved by creating and loading one model per camera stream as opposed to have them all share the same instance of the same model. Can close this now.

**Comment by YashasSamaga** [comment]
I should have told earlier but you could use `cuda-memcheck your_program` to find the source of illegal memory access.

As I told earlier, the illegal memory access probably happened before the `cv::dnn::Net` object was created but the error was reported during its construction as CUDA errors are asynchronous. The CUDA memory check tool can find errors at the correct site.

**Comment by rafale77** [comment]
Just wanted to you folks know that I have tested pytorch on the same ported model and the same loading/inference code not seeing any memory conflicts which enabled me to run the same inference with 6x less memory consumption (I am running inference on 7 camera streams). Basically pytorch enables me to load the model only once and to call inference (forward) simultaneously while another inference is running but opencv crashes out with a memory conflict, forcing me to load multiple copies of the same model in the GPU.
