### ISSUE TITLE
YoloV4 error when running fp32: CUDNN_STATUS_BAD_PARAM in function 'convolve'

### ISSUE THREAD

**Issue by rafale77** [opencv/opencv#17969]
##### System information (version)
- OpenCV => 4.4dev
- Operating System / Platform => Ubuntu 18.04
- Compiler => gcc 7.5
- nVidia Driver: 450.57
- CUDA: 11.0.194GA
- cudnn: 8.0.2GA

##### Detailed description

        cv2.error: OpenCV(4.4.0-dev) /source/opencv/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/convolution.hpp:420: error: (-217:Gpu API call) CUDNN_STATUS_BAD_PARAM in function 'convolve'

##### Steps to reproduce

running YOLOV4 model with this works:

        net = cv2.dnn.readNet('yolov4.weights', 'yolov4.cfg')
        net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
        net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA_FP16)

With this I get the error above

        net = cv2.dnn.readNet('yolov4.weights', 'yolov4.cfg')
        net.setPreferableBackend(cv2.dnn.DNN_BACKEND_CUDA)
        net.setPreferableTarget(cv2.dnn.DNN_TARGET_CUDA)

**Comment by YashasSamaga** [comment]
Was it working before? There is no change mentioned in their documentation.

**Comment by rafale77** [comment]
I just started running this yesterday and I honestly did not pay attention to it. I did upgrade to the latest cudnn midway and started noticing this error.

**Comment by YashasSamaga** [comment]
I am not able to reproduce with cuDNN 8.0.2 with CUDA 10.2. This might be specific to an architecture or device as different algorithms are used on different devices. What device are you using?

**Comment by rafale77** [comment]
I am running on intel x64/RTX2070 within a QEMU VM.

**Comment by YashasSamaga** [comment]
@rafale77 What FPS are you getting with FP16 target? cuDNN 8.0.2 is for some reason 2x slower on GTX 1050 in both OpenCV and Darknet.

**Comment by rafale77** [comment]
Hmm I can't easily answer this question since I am not testing the FPS and am actually implementing it for actual production in my security system with 7 simultaneous camera streams alongside another model. I also never had 7.6.5 as the GPU is a new installation. There was report in the released notes of 8.0.0rc and 8.0.1 about poor performance which were supposed to be addressed in 8.0.2...

**Comment by rafale77** [comment]
Also do I understand it correctly that FP16 switches the processing to tensor cores and FP32 would switch them to the cuda SM cores? This could explain my problem as I may have some driver/library issues?

**Comment by YashasSamaga** [comment]
> Also do I understand it correctly that FP16 switches the processing to tensor cores and FP32 would switch them to the cuda SM cores?

FP32 always uses CUDA cores. FP16 may or may not use tensor cores. This is decided on a per-layer basis.

> This could explain my problem as I may have some driver/library issues?

I don't think this is the problem. cuDNN returned `CUDNN_STATUS_BAD_PARAM` which indicates that OpenCV passed wrong inputs to the cuDNN API. I checked once a few days ago and it seems like OpenCV is conforming to cuDNN's documentation. So I am not really sure if it's a bug in cuDNN or with OpenCV.

I am working on adding support to use the new API that comes with cuDNN instead of the legacy cuDNN 7 API. Hopefully, it might fix this.

**Comment by martinraism** [comment]
I am having the exact same issue on Windows. CUDNN 8, CUDA 10.1, OpenCV4.4, RTX4000.
However, this issue is not happening in two other servers:
1) Ubuntu. CUDNN 7.5. CUDA 10.1. OpenCV 4.4. RTX 2080Ti.
2) Windows. CUDNN 8. CUDA 10.1 OpenCV 4.4. P6000 (Pascal) GPU.
I have debugged the bug and it always crashes in the same convolutional layer:
![LayerCrash](https://user-images.githubusercontent.com/6662996/90622863-02104500-e216-11ea-8f7a-56fb2aad1123.jpg)

I don't know it helps in something. How is the status of this?
Thanks in advance.

**Comment by YashasSamaga** [comment]
I am trying to move to the new v8 API. There isn't sufficient documentation and samples to understand how the new API works. I am waiting for cuDNN team to release a sample (and a new C++ API which they say will be available in a few weeks).

**Comment by grzegorzk** [comment]
I started experiencing the same issue as author of this issue after upgrading my system to CUDA 11 (I'm on Arch Linux).

Before upgrading (this was cuda 10.2) I was on Opencv 4.2.0 and everything worked fine (no errors when running inference using yolov3 models on CUDA backend).

I have built Opencv 4.2.0 again (hoping I'm experiencing corrupted build), and then 4.4.0, and then I switched to today's HEAD. Each time I see the same issue.

These are my versions of CUDA/CUDNN libs:
```
libcudart.so.11.0 -> libcudart.so.11.0.194
libcuda.so.1 -> libcuda.so.450.66
libcudart.so.11.0 -> libcudart.so.11.0.194
libcudnn_adv_infer.so.8 -> libcudnn_adv_infer.so.8.0.2
libcudnn_adv_train.so.8 -> libcudnn_adv_train.so.8.0.2
libcudnn_cnn_infer.so.8 -> libcudnn_cnn_infer.so.8.0.2
libcudnn.so.8 -> libcudnn.so.8.0.2
libcudnn_ops_infer.so.8 -> libcudnn_ops_infer.so.8.0.2
libcudnn_cnn_train.so.8 -> libcudnn_cnn_train.so.8.0.2
libcudnn_ops_train.so.8 -> libcudnn_ops_train.so.8.0.2
```

I tried the same thing as OP and when I change tartegId to DNN_TARGET_CUDA_FP16 Opencv is not failing.

**Comment by YashasSamaga** [comment]
The convolution layer in question uses cuDNN for plain convolution. The activation or bias addition is not fused. However, let's make sure that an accidental fusion is not the source of the bug: try executing the model with `net.enableFusion(false)`.

Has anyone tried with cuDNN 7 or cuDNN 8 RC?

**Comment by YashasSamaga** [comment]
The only thing that varies across devices is the choice of the convolution algorithm. This is picked by cuDNN. cuDNN does not throw `CUDNN_STATUS_BAD_PARAM` on my devices. Moreover, I think all of you are experiencing the issue consistently (i.e. it's not randomly happening).

I think the convolution parameters (padding, shape calculations, etc) are mostly correct as this does not vary across devices and cuDNN is not complaining on my device. The issue is probably with the algorithm chosen or workspace issue (but workspace problems would be caught before the cuDNN API is invoked).

Is anyone willing to volunteer to run an instrumented version of the CUDA backend? I can make a branch off master which would dump lots of debug information. This might help isolate the source of the problem.

**Comment by H-s-O** [comment]
I've got the same error when using the [MiDAS](https://github.com/intel-isl/MiDaS) model; but it works when using target `DNN_TARGET_CUDA_FP16`.

- AMD Ryzen 7 3700X 8-Core
- Titan RTX
- CUDA 11.0.3 (Update 1)
- cuDNN 8.0.2.39

**Comment by YashasSamaga** [comment]
> In prior versions of cuDNN, API functions cudnnGetConvolution*Algorithm_v7() return a workspace size in the result for algo1 that is inconsistent with the result of the corresponding cudnnGet*Workspace() calls if the math type of the convolution descriptor is set to CUDNN_FMA_MATH. This issue has been fixed in this release. 

This is applicable to the current mechanism used by OpenCV to choose convolution algorithms. Please check if cuDNN 8.0.3 has fixed this problem.

**Comment by eriklogtenberg** [comment]
I get the same error with:
- libcudnn8-8.0.3.33-1.cuda11.0.x86_64
- OpenCV 4.5.0
- cuda-11.1.0-1.x86_64
- GTX 1070 in a i7-3930K machine, running Fedora 32

cv2.error: OpenCV(4.5.0) opencv-4.5.0/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/convolution.hpp:411: error: (-217:Gpu API call) CUDNN_STATUS_BAD_PARAM in function 'convolve'

I am using VGG_VOC0712Plus_SSD_512x512_ft_iter_160000.caffemodel from: https://github.com/weiliu89/caffe/tree/ssd

**Comment by alalek** [comment]
@eriklogtenberg Please try to run OpenCV DNN tests first.

**Comment by eriklogtenberg** [comment]
Well, I mean I can run Yolov3 Coco and MobileNetSSD just fine, and they're properly running on the GPU, so I know this OpenCV + cuDNN setup is working.

**Comment by nguyen14ck** [comment]
I have the same error with:
+ CentOS 7.3
+ Cuda 11.1
+ CuDnn 8.0.5
Btw, @martinraism, what tool did you use to visualize the network graph & debug? Thank you!

**Comment by YashasSamaga** [comment]
Do you get the same error when you try with darknet?

**Comment by martinraism** [comment]
> I have the same error with:
> 
> * CentOS 7.3
> * Cuda 11.1
> * CuDnn 8.0.5
>   Btw, @martinraism, what tool did you use to visualize the network graph & debug? Thank you!

I used https://github.com/lutzroeder/Netron

**Comment by H-s-O** [comment]
Is this now fixed if closed?!

**Comment by alalek** [comment]
CUDNN 8 support is tracked here: #17496
