### ISSUE TITLE
terminate called after throwing an instance of 'cv::dnn::cuda4dnn::csl::cudnn::cuDNNException

### ISSUE THREAD

**Issue by AD2605** [opencv/opencv#18187]
##### System information (version)

- OpenCV => :4.4.0:
- Operating System / Platform =>  Ubuntu 20.04
- Compiler =>  GCC 8.4

##### Detailed description
I am loading a pre-trained SSD from TensorFlow and setting the target as preferred backend as CUDA. I am running Cuda 10.2 with cuDNN 8.0.2 and I have built OpenCV. Following code to load the model  
```
    cv::dnn::Net net = cv::dnn::readNetFromTensorflow("/Models/frozen_inference_graph.pb",
                                        "/graph.pbtxt");
    net.setPreferableBackend(cv::dnn::DNN_BACKEND_CUDA); 
    net.setPreferableTarget(cv::dnn::DNN_TARGET_CUDA); 
```
And I get the following error - 

```
terminate called after throwing an instance of 'cv::dnn::cuda4dnn::csl::cudnn::cuDNNException'

what():  OpenCV(4.4.0) /home/atharva/opencv-4.4.0/modules/dnn/src/layers/../cuda4dnn/primitives/../csl/cudnn/convolution.hpp:420: error: (-217:Gpu API call) CUDNN_STATUS_BAD_PARAM in function 'convolve'
```
Could you please point what could be goig wrong?

##### Issue submission checklist

 - [ yes] I report the issue, it's not a question
   
 - [yes ] I checked the problem with documentation, FAQ, open issues,
       answers.opencv.org, Stack Overflow, etc and have not found solution
   
 - [ yes] I updated to latest OpenCV version and the issue is still there
   
 - [ yes] There is reproducer code and related data files: videos, images, onnx, etc

**Comment by YashasSamaga** [comment]
might be a duplicate of #17969 

Can you try with previous version of cuDNN 8 or cuDNN 7?

**Comment by AD2605** [comment]
Had a look at it and tried it with FP16 and it works, I will try with the previous versions of cuDNN.. .
PS - Since I built the library from source on my system, reverting to older versions should not make a difference correct? also I would have to build it again right?

**Comment by YashasSamaga** [comment]
@AD2605 You will have to rebuild. OpenCV will throw an exception if the cuDNN version used during build does not match with the cuDNN runtime version used.

**Comment by AD2605** [comment]
@YashasSamaga it did not throw an exception when I was building it, so is it possible there might be another reason for the error other than cuDNN version?, anyways I wil rebuild and try it with other versions

**Comment by YashasSamaga** [comment]
>  it did not throw an exception when I was building it, so is it possible there might be another reason for the error other than cuDNN version?, anyways I wil rebuild and try it with other versions

Exceptions are thrown when you attempt to use the CUDA backend. Ensure that the cuDNN CMake variables point to the intended version of cuDNN while building.

**Comment by YashasSamaga** [comment]
> In prior versions of cuDNN, API functions cudnnGetConvolution*Algorithm_v7() return a workspace size in the result for algo1 that is inconsistent with the result of the corresponding cudnnGet*Workspace() calls if the math type of the convolution descriptor is set to CUDNN_FMA_MATH. This issue has been fixed in this release. 

This fix is relevant for FP32 target. Please try with cuDNN 8.0.3.
