### ISSUE TITLE
Unable to cross compile for aarch64 CUDA, cuda not found

### ISSUE THREAD

**Issue by cyrusbehr** [opencv/opencv#19986]
I am trying to cross compile opencv with cuda support for aarch64 target. I am attempting to compile in [this](https://github.com/apache/incubator-mxnet/blob/e8ad36aeaa5de61ca073acbe598d853f63262721/ci/docker/Dockerfile.build.jetson) image here from the mxnet github repo. They have already installed all necessary cuda libs in that image, including cuda-10.2, with `aarch64-linux` target.

Here is my cmake commands. As you can see, I am also compiling a few modules from the contrib repo.

```
cmake -D CUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda/targets/aarch64-linux  -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE} -DCMAKE_LIBRARY_PATH=/usr/local/cuda/targets/aarch64-linux/lib/stubs -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.1/modules -D WITH_CUDA=ON -D opencv_cudev=ON -DCUDA_ARCH_BIN='7.2' -DBUILD_opencv_cudev=ON -D WITH_CAROTENE=OFF -D BUILD_LIST=core,imgcodecs,imgproc,calib3d,videoio,highgui,cudev,cudaimgproc,cudaarithm,cudawarping -D BUILD_SHARED_LIBS=OFF -D CMAKE_BUILD_TYPE=RELEASE -D BUILD_DOCS=OFF -D BUILD_EXAMPLES=OFF -D BUILD_opencv_apps=OFF -D BUILD_opencv_python2=OFF -D BUILD_opencv_python3=OFF -D BUILD_PERF_TESTS=OFF -D BUILD_TESTS=OFF -D FORCE_VTK=OFF -D WITH_FFMPEG=OFF -D WITH_GDAL=OFF -D WITH_IPP=OFF -D WITH_OPENEXR=OFF -D WITH_OPENGL=OFF -D WITH_QT=OFF -D WITH_TBB=OFF -D WITH_XINE=OFF -D BUILD_JPEG=ON -D BUILD_ZLIB=ON -D BUILD_PNG=ON -D BUILD_TIFF=ON -D BUILD_BUILD_JASPER=OFF -D WITH_ITT=OFF -D WITH_LAPACK=OFF -D WITH_OPENCL=OFF -D WITH_TIFF=ON -D WITH_PNG=ON -D WITH_OPENCLAMDFFT=OFF -D WITH_OPENCLAMDBLAS=OFF -D WITH_VA_INTEL=OFF -D WITH_WEBP=OFF -D WITH_JASPER=OFF ..

```

The contents of the ${CMAKE_TOOLCHAIN_FILE} file are as follows:

```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR "aarch64")
set(CMAKE_C_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER aarch64-linux-gnu-g++)
set(CMAKE_CUDA_COMPILER nvcc)
set(CMAKE_CUDA_HOST_COMPILER aarch64-linux-gnu-gcc)
set(CMAKE_FIND_ROOT_PATH "/usr/aarch64-linux-gnu")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

```

When the CMake command is run, cuda is not found for some reason:
```
CMake Warning at cmake/OpenCVFindLibsPerf.cmake:35 (message):
  OpenCV is not able to find/configure CUDA SDK (required by WITH_CUDA).

  CUDA support will be disabled in OpenCV build.

  To eliminate this warning remove WITH_CUDA=ON CMake configuration option.

Call Stack (most recent call first):
  CMakeLists.txt:786 (include)

```

This is strange considering I was able to compile mxnet for aarch64 with cuda support in the same environment. 
Any ideas? 

**EDIT**

Sorry I should mention which version of OpenCV I am using: 4.1.1

**Comment by cyrusbehr** [comment]
Hmm I'll need to check. 

In the meantime, is there a docker container you have for cross compiling for aarch64 cuda on an x86 host where the environment is properly set up that I could use, perhaps you have an image being used for your CI builds?

**Comment by cyrusbehr** [comment]
I tried the solve in [this](https://forums.developer.nvidia.com/t/cross-compile-opencv4-for-jetson-nano/123220/7?u=cyruspk4w6) post and it worked.

I basically added `set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")` to the root OpenCV CMakeLists.txt.

**Comment by cyrusbehr** [comment]
Correction, I needed to add `set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/")` to the top of `cmake/OpenCVDetectCUDA.cmake`, and I also needed to use the OpenCV toolchain file instead of my own:
`-DCMAKE_TOOLCHAIN_FILE=../platforms/linux/aarch64-gnu.toolchain.cmake`
