### ISSUE TITLE
build with cuda error 

### ISSUE THREAD

**Issue by AhmedEmadEldinHussin** [opencv/opencv#23374]
### System Information

OpenCV version: 4.7.0
Operating System / Platform: Ubuntu 22.04
Compiler & compiler version: GCC 11.3.0
nvidia-driver: 510
cuda-version: 11.6
cudnn: 8.7

### Detailed description

HI , I got this error while compiling the opencv with gpu

cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=ON -D WITH_CUDNN=ON -D WITH_CUBLAS=ON -D WITH_TBB=ON -D OPENCV_DNN_CUDA=ON -D OPENCV_ENABLE_NONFREE=ON -D CUDA_ARCH_BIN=7.5 -D OPENCV_EXTRA_MODULES_PATH=$HOME/opencv_contrib/modules -D BUILD_EXAMPLES=OFF -D HAVE_opencv_python3=ON ..
 

 CMake Error at cuda_compile_1_generated_gpu_mat.cu.o.RELEASE.cmake:282 (message):
  Error generating file
  /home/ahmed/opencv/opencv-4.7.0/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o

### Steps to reproduce

 CMake Error at cuda_compile_1_generated_gpu_mat.cu.o.RELEASE.cmake:282 (message):
  Error generating file
  /home/ahmed/opencv/opencv-4.7.0/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o
c)

**Comment by cudawarped** [comment]
Can you post the CMake configuration output and the whole build errror.

**Comment by AhmedEmadEldinHussin** [comment]
cmake configuration


cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local -D WITH_CUDA=ON -D WITH_CUDNN=ON -D WITH_CUBLAS=ON -D WITH_TBB=ON -D OPENCV_DNN_CUDA=ON -D OPENCV_ENABLE_NONFREE=ON -D CUDA_ARCH_BIN=7.5 -D OPENCV_EXTRA_MODULES_PATH=$HOME/opencv/opencv_contrib/modules -D BUILD_EXAMPLES=OFF -D HAVE_opencv_python3=ON ..


this all the output
<pre>[  0%] Built target opencv_dnn_plugins
[  0%] Built target opencv_videoio_plugins
[  0%] Built target opencv_highgui_plugins
[  0%] <font color="#26A269">Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/ittnotify_static.c.o</font>
[  0%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/thread.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/quirc/CMakeFiles/quirc.dir/src/decode.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_core.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/bio.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_color_convert_all.c.o</font>
[  1%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/any_lite.cc.o</font>
[  1%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/arena.cc.o</font>
[  1%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/arenastring.cc.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_color_convert_rgbs.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/cio.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_bilateral.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_box.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/dwt.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/event.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_canny.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_gaussian.c.o</font>
[  1%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/alloc.cpp.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ittnotify/CMakeFiles/ittnotify.dir/src/ittnotify/jitprofiling.c.o</font>
[  1%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/assert.cpp.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_general.c.o</font>
[  1%] <font color="#26A269"><b>Linking C static library ../lib/libittnotify.a</b></font>
[  1%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/check_cycles.cpp.o</font>
[  1%] Built target ittnotify
[  1%] <font color="#12488B"><b>Generate files for Python bindings and documentation</b></font>
[  1%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/edge.cpp.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_laplacian.c.o</font>
[  1%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set.cc.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/quirc/CMakeFiles/quirc.dir/src/quirc.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_morphology.c.o</font>
[  1%] <font color="#26A269">Building C object 3rdparty/quirc/CMakeFiles/quirc.dir/src/version_db.c.o</font>
[  2%] <font color="#26A269"><b>Linking C static library ../lib/libquirc.a</b></font>
[  2%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/execution_engine.cpp.o</font>
[  2%] Built target quirc
[  2%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_util.cc.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_scharr.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_filter_sobel.c.o</font>
[  2%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/implicit_weak_message.cc.o</font>
[  2%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/coded_stream.cc.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_channel.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_make_border.c.o</font>
Note: Class cv::Feature2D has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::Algorithm, cv::class, cv::Feature2D, cv::Algorithm
      Only the first base class will be used
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_merge.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_copy_split.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_scale.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_set.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_set_channel.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_op_swap_channels.c.o</font>
[  2%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/graph.cpp.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/image.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/invert.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_transform_mirror.c.o</font>
[  2%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/memory_accessor.cpp.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/j2k.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_transform_resize.c.o</font>
[  2%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/jp2.c.o</font>
Note: Class cv::detail::GraphCutSeamFinder has more than 1 base class (not supported by Python C extensions)
      Bases:  cv::detail::GraphCutSeamFinderBase, cv::detail::SeamFinder
      Only the first base class will be used
[  2%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_transform_rotate.c.o</font>
[  3%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_image_transform_warpaffine.c.o</font>
[  3%] <font color="#26A269">Building C object 3rdparty/ippiw/CMakeFiles/ippiw.dir/src/iw_own.c.o</font>
[  3%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/io_win32.cc.o</font>
[  3%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/strtod.cc.o</font>
[  3%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/mct.c.o</font>
[  3%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream.cc.o</font>
[  3%] <font color="#26A269"><b>Linking C static library ../lib/libippiw.a</b></font>
[  3%] Built target ippiw
[  3%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/memory_descriptor.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object modules/cudev/CMakeFiles/opencv_cudev.dir/src/stub.cpp.o</font>
[  4%] <font color="#26A269"><b>Linking CXX shared library ../../lib/libopencv_cudev.so</b></font>
[  4%] Built target opencv_cudev
[  4%] <font color="#12488B"><b>Processing OpenCL kernels (core)</b></font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream_impl.cc.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/memory_descriptor_ref.cpp.o</font>
[  4%] <font color="#12488B"><b>Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.o</b></font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/zero_copy_stream_impl_lite.cc.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/memory_descriptor_view.cpp.o</font>
[  4%] Built target gen_opencv_python_source
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/metadata.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/metatypes.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/map.cc.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/node.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/message_lite.cc.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/passes/communications.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/search.cpp.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/subgraphs.cpp.o</font>
[  4%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/mqc.c.o</font>
[  4%] <font color="#26A269">Building CXX object CMakeFiles/ade.dir/3rdparty/ade/ade-0.1.2a/sources/ade/source/topological_sort.cpp.o</font>
[  4%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/openjpeg.c.o</font>
[  4%] <font color="#12488B"><b>Building NVCC (Device) object modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat_nd.cu.o</b></font>
[  4%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/opj_clock.c.o</font>
[  4%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/pi.c.o</font>
[  4%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/t1.c.o</font>
In file included from <b>/usr/include/string.h:535</b>,
                 from <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/stubs/port.h:39</b>,
                 from <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/stubs/common.h:48</b>,
                 from <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/message_lite.h:45</b>,
                 from <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/message_lite.cc:36</b>:
In function ‘<b>void* memcpy(void*, const void*, size_t)</b>’,
    inlined from ‘<b>uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/io/coded_stream.h:706:16</b>,
    inlined from ‘<b>virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) const</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/implicit_weak_message.h:84:28</b>,
    inlined from ‘<b>bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/message_lite.cc:412:30</b>,
    inlined from ‘<b>bool google::protobuf::MessageLite::SerializeToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/message_lite.cc:396:42</b>:
<b>/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33:</b> <font color="#A347BA"><b>warning: </b></font>‘void* __builtin___memcpy_chk(void*, const void*, long unsigned i<b>nt, long unsigned int)</b><font color="#A347BA"><b>’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 92233720368547</b></font>75807 [<font color="#A347BA"><b>-Wstringop-overflow=</b></font>]
   29 |   return <font color="#A347BA"><b>__builtin___memcpy_chk (__dest, __src, __len,</b></font>
      |          <font color="#A347BA"><b>~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~</b></font>
   30 | <font color="#A347BA"><b>                                 __glibc_objsize0 (__dest))</b></font>;
      |                                  <font color="#A347BA"><b>~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
In function ‘<b>void* memcpy(void*, const void*, size_t)</b>’,
    inlined from ‘<b>uint8_t* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, uint8_t*)</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/io/coded_stream.h:706:16</b>,
    inlined from ‘<b>virtual uint8_t* google::protobuf::internal::ImplicitWeakMessage::_InternalSerialize(uint8_t*, google::protobuf::io::EpsCopyOutputStream*) const</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/implicit_weak_message.h:84:28</b>,
    inlined from ‘<b>bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const</b>’ at <b>/home/ahmed/opencv/opencv-4.7.0/3rdparty/protobuf/src/google/protobuf/message_lite.cc:412:30</b>:
<b>/usr/include/x86_64-linux-gnu/bits/string_fortified.h:29:33:</b> <font color="#A347BA"><b>warning: </b></font>‘void* __builtin___memcpy_chk(void*, const void*, long unsigned i<b>nt, long unsigned int)</b><font color="#A347BA"><b>’ specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 92233720368547</b></font>75807 [<font color="#A347BA"><b>-Wstringop-overflow=</b></font>]
   29 |   return <font color="#A347BA"><b>__builtin___memcpy_chk (__dest, __src, __len,</b></font>
      |          <font color="#A347BA"><b>~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~</b></font>
   30 | <font color="#A347BA"><b>                                 __glibc_objsize0 (__dest))</b></font>;
      |                                  <font color="#A347BA"><b>~~~~~~~~~~~~~~~~~~~~~~~~~~</b></font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/parse_context.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/repeated_field.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/repeated_ptr_field.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/bytestream.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/common.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/int128.cc.o</font>
[  4%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/status.cc.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/stringpiece.cc.o</font>
[  5%] <font color="#26A269"><b>Linking CXX static library 3rdparty/lib/libade.a</b></font>
[  5%] Built target ade
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/stringprintf.cc.o</font>
[  5%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/t2.c.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/structurally_valid.cc.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/strutil.cc.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format_lite.cc.o</font>
[  5%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/tcd.c.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/any.cc.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.cc.o</font>
[  5%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor.pb.cc.o</font>
[  5%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/tgt.c.o</font>
[  5%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/function_list.c.o</font>
[  6%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/opj_malloc.c.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/descriptor_database.cc.o</font>
[  6%] <font color="#26A269">Building C object 3rdparty/openjpeg/openjp2/CMakeFiles/libopenjp2.dir/sparse_array.c.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/dynamic_message.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/extension_set_heavy.cc.o</font>
[  6%] <font color="#26A269"><b>Linking C static library ../../lib/liblibopenjp2.a</b></font>
[  6%] Built target libopenjp2
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/generated_message_reflection.cc.o</font>
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&amp;&amp; __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&amp;&amp; __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
<font color="#C01C28">CMake Error at cuda_compile_1_generated_gpu_mat_nd.cu.o.RELEASE.cmake:282 (message):</font>
<font color="#C01C28">  Error generating file</font>
<font color="#C01C28">  /home/ahmed/opencv/opencv-4.7.0/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat_nd.cu.o</font>


make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:84: modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat_nd.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/io/tokenizer.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/map_field.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/message.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/reflection_ops.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/stubs/substitute.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/text_format.cc.o</font>
/usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
  435 |         function(_Functor&amp;&amp; __f)
      |                                                                                                                                                 ^ 
/usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
/usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
  530 |         operator=(_Functor&amp;&amp; __f)
      |                                                                                                                                                  ^ 
/usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/unknown_field_set.cc.o</font>
[  6%] <font color="#26A269">Building CXX object 3rdparty/protobuf/CMakeFiles/libprotobuf.dir/src/google/protobuf/wire_format.cc.o</font>
<font color="#C01C28">CMake Error at cuda_compile_1_generated_gpu_mat.cu.o.RELEASE.cmake:282 (message):</font>
<font color="#C01C28">  Error generating file</font>
<font color="#C01C28">  /home/ahmed/opencv/opencv-4.7.0/build/modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/./cuda_compile_1_generated_gpu_mat.cu.o</font>


make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/build.make:77: modules/core/CMakeFiles/cuda_compile_1.dir/src/cuda/cuda_compile_1_generated_gpu_mat.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:4019: modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  6%] <font color="#26A269"><b>Linking CXX static library ../lib/liblibprotobuf.a</b></font>
[  6%] Built target libprotobuf
make: *** [Makefile:166: all] Error 2
</pre>

**Comment by LaurentBerger** [comment]
may be [this ](https://github.com/NVlabs/instant-ngp/issues/119)can help you

**Comment by AhmedEmadEldinHussin** [comment]
Thanks It worked for me

**Comment by qimao7213** [comment]
hi, how did you fix your probelm? i met the same probelm with yours.

**Comment by daylight0** [comment]
> hi, how did you fix your probelm? i met the same probelm with yours.


Try lowering the versions of GCC and G++ and see if it helps.
