### ISSUE TITLE
Link errors “undefined reference to cublasLtSetEnvironmentMode” & “cublasLtGetEnvironmentMode” when building OpenCV 4.13.0 with CUDA 12.9 on Ubuntu 24.04

### ISSUE THREAD

**Issue by tradzero** [opencv/opencv#27639]
### System Information

OpenCV: 4.13.0
OS: Ubuntu 24.04.1 LTS
Compiler: GCC 13.3.0
Python: 3.10.18
CUDA Toolkit: 12.9 (installed under /usr/local/cuda)
GPU: NVIDIA RTX 5090
Driver: 575.64.03
CPU: AMD EPYC 7302P

LD configuration:
```bash
ldconfig -p | grep -E 'cublasLt|cublas'

libcublasLt.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12
libcublasLt.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so
libcublas.so.12 (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so.12
libcublas.so (libc6,x86-64) => /usr/local/cuda/targets/x86_64-linux/lib/libcublas.so
```

### Detailed description

I’m trying to build OpenCV 4.13.0 with CUDA support on Ubuntu 24.04.1 using CUDA 12.9 and GCC 13.3.0, but the linker fails for the cudafilters and cudaarithm benchmarks:
```
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: 
    undefined reference to `cublasLtSetEnvironmentMode@libcublasLt.so.12'
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: 
    undefined reference to `cublasLtGetEnvironmentMode@libcublasLt.so.12'
collect2: error: ld returned 1 exit status
...
make[2]: *** [modules/cudafilters/.../bin/opencv_perf_cudafilters] Error 1
make[2]: *** [modules/cudaarithm/.../bin/opencv_perf_cudaarithm] Error 1
```

### Steps to reproduce

git clone  https://github.com/opencv/opencv.git
git clone  https://github.com/opencv/opencv_contrib.git
cd opencv && mkdir build && cd build

cmake .. \
  -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D WITH_CUDA=ON \
  -D WITH_CUDNN=ON \
  -D WITH_CUBLAS=ON \
  -D WITH_TBB=ON \
  -D OPENCV_DNN_CUDA=ON \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D CUDA_ARCH_BIN=12.0 \
  -D OPENCV_EXTRA_MODULES_PATH=<path-to-opencv_contrib>/modules \
  -D BUILD_EXAMPLES=OFF \
  -D HAVE_opencv_python3=ON \
  -D BUILD_TESTS=OFF \
  -D WITH_FFMPEG=ON

make -j$(nproc)

### Issue submission checklist

- [x] I report the issue, it's not a question
- [x] I checked the problem with documentation, FAQ, open issues, forum.opencv.org, Stack Overflow, etc and have not found any solution
- [x] I updated to the latest OpenCV version and the issue is still there
- [ ] There is reproducer code and related data files (videos, images, onnx, etc)

**Comment by tradzero** [comment]
i also tried modify /etc/ld.so.conf.d/000_cuda.conf & /etc/ld.so.conf.d/988_cuda-12.conf change /usr/local/cuda/targets/x86_64-linux/lib to /usr/local/cuda/lib64,  problem also shown, and i sure two directories have lib file.

**Comment by tradzero** [comment]
> I understand there was a problem with the compilation process. It seems the issue stemmed from a mistake during the configuration. The settings were not adjusted correctly, which led to the compilation errors. Careful review of the instructions might have helped prevent the problem. Ultimately, the problem was caused by the actions taken.

Thanks for replying. I followed this [article](https://medium.com/@juancrrn/installing-opencv-4-with-cuda-in-ubuntu-20-04-fde6d6a0a367) with a few adjustments (e.g. using a self-built FFmpeg). Could you point out which part of my configuration might have caused the compilation errors? Thanks again.

**Comment by asmorkalov** [comment]
cc @cudawarped

**Comment by cudawarped** [comment]
@asmorkalov Unable to reproduce on Ubuntu 22.04 with the latest version of OpenCV and

```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:21:03_PDT_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0
```

If I can I have chance I will try to test with 

> OS: Ubuntu 24.04.1 LTS
> Compiler: GCC 13.3.0

@tradzero Is it possible you have installed one minor update of the CUDA toolkit over another?

**Comment by tradzero** [comment]
@cudawarped No, that’s not the case. I have already tried fully removing all CUDA files and drivers, and then reinstalling everything from scratch. If there is any specific environment information or other details you need, please let me know.

nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Wed_Apr__9_19:24:57_PDT_2025
Cuda compilation tools, release 12.9, V12.9.41
Build cuda_12.9.r12.9/compiler.35813241_0

**Comment by cudawarped** [comment]
> If there is any specific environment information or other details you need, please let me know.

Only the [post installation actions](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#post-installation-actions).  How did you install CUDA?  You are using a different minor version of the Toolkit which I have probably never tested so it could be that.

**Comment by tradzero** [comment]
> > If there is any specific environment information or other details you need, please let me know.
> 
> Only the [post installation actions](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#post-installation-actions). How did you install CUDA? You are using a different minor version of the Toolkit which I have probably never tested so it could be that.
I install cuda by [this](https://developer.nvidia.com/cuda-12-9-0-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local), I am trying get 12.9 update 1. 

2025/08/08 20:33 update:

i had upgrade by install [12-9-1](https://developer.nvidia.com/cuda-12-9-1-download-archive?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=24.04&target_type=deb_local), and run 
$ sudo ldconfig
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Tue_May_27_02:21:03_PDT_2025
Cuda compilation tools, release 12.9, V12.9.86
Build cuda_12.9.r12.9/compiler.36037853_0

and problem still happened 😂.
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: undefined reference to `cublasLtSetEnvironmentMode@libcublasLt.so.12'
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: undefined reference to `cublasLtGetEnvironmentMode@libcublasLt.so.12'
collect2: error: ld returned 1 exit status
make[2]: *** [modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/build.make:174: bin/opencv_perf_cudaarithm] Error 1
make[1]: *** [CMakeFiles/Makefile2:3919: modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/all] Error 2

**Comment by cudawarped** [comment]
Did you [remove the existing CUDA Toolkit](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/#removing-cuda-toolkit) first? I'm asking because that symbol doesn't exist in CUDA 12.8 so there is a chance that the linker is finding _libcublasLt.so.12_ from an older version of the CUDA toolkit.

Can you see if the `cublasLtSetEnvironmentMode`  symbol exists in your _libcublasLt.so.12_

```
 nm -D /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12 | grep cublasLtSetEnvironmentMode
```

**Comment by tradzero** [comment]
@cudawarped  Thank you for your continued assistance. When I submitted the issue, I had fully uninstalled all CUDA components and drivers and then reinstalled everything from scratch. For this upgrade from CUDA 12.9.0 to 12.9.1, I did not uninstall the previous version first; I will try uninstalling and reinstalling.

Additionally, I ran the following command to check whether the cublasLtSetEnvironmentMode symbol is present:

nm -D /usr/local/cuda/targets/x86_64-linux/lib/libcublasLt.so.12 | grep cublasLtSetEnvironmentMode
The output confirms that the symbol exists:

0000000000f9a210 T cublasLtSetEnvironmentMode@@libcublasLt.so.12

**Comment by cudawarped** [comment]
The error seems to imply that you are linking against an earlier version of `libcublas`. Is there a chance you have another version of the CUDA Toolkit installed perhaps through conda or another package manager?  If this is the case it should be easy to check with
```
cat OPENCV_BUILD_DIR/CMakeVars.txt | grep CUDA_CUBLAS
```

**Comment by tradzero** [comment]
@cudawarped 
Yes, I do have CUDA 12.8 installed via conda in my environment. For various reasons I overlooked this—sorry about that. This seems to be the root cause. With the help of an AI assistant I ran:
```
make VERBOSE=1 opencv_perf_cudaarithm -j1
```
and saw the failing build log:
```
cd /home/zero/dev/opencv/build/modules/cudaarithm && /usr/bin/c++ -D_USE_MATH_DEFINES -D__OPENCV_BUILD=1 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/zero/dev/opencv/hal/ipp/include -I/home/zero/dev/opencv/build/3rdparty/ippicv/ippicv_lnx/icv/include -I/home/zero/dev/opencv/build/3rdparty/ippicv/ippicv_lnx/iw/include -I/home/zero/dev/opencv/build -I/home/zero/dev/opencv_contrib/modules/cudaarithm/include -I/home/zero/dev/opencv/build/modules/cudaarithm -I/home/zero/dev/opencv_contrib/modules/cudev/include -I/home/zero/dev/opencv/modules/core/include -I/home/zero/dev/opencv/modules/ts/include -I/home/zero/dev/opencv/modules/imgcodecs/include -I/home/zero/dev/opencv/modules/imgproc/include -I/home/zero/dev/opencv/modules/videoio/include -I/home/zero/dev/opencv/modules/highgui/include -isystem /usr/local/cuda/include -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-undef -Wno-missing-declarations -Wno-shadow -O3 -DNDEBUG  -DNDEBUG -std=c++11 -fPIE -MD -MT modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_reductions.cpp.o -MF CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_reductions.cpp.o.d -o CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_reductions.cpp.o -c /home/zero/dev/opencv_contrib/modules/cudaarithm/perf/perf_reductions.cpp
[100%] Linking CXX executable ../../bin/opencv_perf_cudaarithm
cd /home/zero/dev/opencv/build/modules/cudaarithm && /usr/bin/cmake -E cmake_link_script CMakeFiles/opencv_perf_cudaarithm.dir/link.txt --verbose=1
/usr/bin/c++    -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Winit-self -Wpointer-arith -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -Wno-undef -Wno-missing-declarations -Wno-shadow -O3 -DNDEBUG  -DNDEBUG   -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_arithm.cpp.o CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_core.cpp.o CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_element_operations.cpp.o CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_main.cpp.o CMakeFiles/opencv_perf_cudaarithm.dir/perf/perf_reductions.cpp.o -o ../../bin/opencv_perf_cudaarithm  -Wl,-rpath,/home/zero/dev/opencv/build/lib:/home/zero/miniconda3/envs/corev2/lib ../../lib/libopencv_ts.a ../../lib/libopencv_cudaarithm.so.4.13.0 ../../lib/libopencv_highgui.so.4.13.0 -ldl -lm -lpthread -lrt ../../3rdparty/lib/libippiw.a ../../3rdparty/ippicv/ippicv_lnx/icv/lib/intel64/libippicv.a -lcudart_static -ldl -lrt -lnppc -lnppial -lnppicc -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcudnn -lcufft -L/usr/local/cuda/lib64 -L/usr/lib/x86_64-linux-gnu ../../lib/libopencv_videoio.so.4.13.0 ../../lib/libopencv_imgcodecs.so.4.13.0 ../../lib/libopencv_imgproc.so.4.13.0 -ldl -lm -lpthread -lrt -lcudart_static -ldl -lm -lpthread -lrt -lcudart_static -lnppc -lnppial -lnppicc -lnppidei -lnppif -lnppig -lnppim -lnppist -lnppisu -lnppitc -lnpps -lcublas -lcudnn -lcufft ../../3rdparty/lib/libipphal.a ../../3rdparty/lib/libippiw.a ../../3rdparty/ippicv/ippicv_lnx/icv/lib/intel64/libippicv.a ../../lib/libopencv_core.so.4.13.0 ../../lib/libopencv_cudev.so.4.13.0 -Wl,-rpath-link,/home/zero/miniconda3/envs/corev2/lib
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: undefined reference to `cublasLtSetEnvironmentMode@libcublasLt.so.12'
/usr/bin/ld: /usr/local/cuda/lib64/libcublas.so: undefined reference to `cublasLtGetEnvironmentMode@libcublasLt.so.12'
collect2: error: ld returned 1 exit status
make[3]: *** [modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/build.make:174: bin/opencv_perf_cudaarithm] Error 1
make[3]: Leaving directory '/home/zero/dev/opencv/build'
make[2]: *** [CMakeFiles/Makefile2:3919: modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/all] Error 2
make[2]: Leaving directory '/home/zero/dev/opencv/build'
make[1]: *** [CMakeFiles/Makefile2:3926: modules/cudaarithm/CMakeFiles/opencv_perf_cudaarithm.dir/rule] Error 2
make[1]: Leaving directory '/home/zero/dev/opencv/build'
make: *** [Makefile:433: opencv_perf_cudaarithm] Error 2
```
It looks like when the conda environment is activated, the rpath gets pointed to conda’s libs.

Then I ran:
```
cat OPENCV_BUILD_DIR/CMakeVars.txt | grep CUDA_CUBLAS
```
and got:
```
CUDA_CUBLAS_LIBRARIES=/usr/local/cuda/lib64/libcublas.so
```
However, I still believe the issue is the rpath being polluted by the activated conda environment.

Anyway, thank you very much for your help over the past few days.
